<?php

use App\Machine;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MachinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $machines = [
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.11',
                'machine_type' => 'rw',
                'machine_name' => 'Washer 1',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.12',
                'machine_type' => 'rw',
                'machine_name' => 'Washer 2',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.13',
                'machine_type' => 'rw',
                'machine_name' => 'Washer 3',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.14',
                'machine_type' => 'rw',
                'machine_name' => 'Washer 4',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.15',
                'machine_type' => 'rw',
                'machine_name' => 'Washer 5',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.31',
                'machine_type' => 'rd',
                'machine_name' => 'Dryer 1',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.32',
                'machine_type' => 'rd',
                'machine_name' => 'Dryer 2',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.33',
                'machine_type' => 'rd',
                'machine_name' => 'Dryer 3',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.34',
                'machine_type' => 'rd',
                'machine_name' => 'Dryer 4',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.35',
                'machine_type' => 'rd',
                'machine_name' => 'Dryer 5',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.21',
                'machine_type' => 'tw',
                'machine_name' => 'Titan Washer 1',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.22',
                'machine_type' => 'tw',
                'machine_name' => 'Titan Washer 2',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.23',
                'machine_type' => 'tw',
                'machine_name' => 'Titan Washer 3',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.24',
                'machine_type' => 'tw',
                'machine_name' => 'Titan Washer 4',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.25',
                'machine_type' => 'tw',
                'machine_name' => 'Titan Washer 5',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.41',
                'machine_type' => 'td',
                'machine_name' => 'Titan Dryer 1',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.42',
                'machine_type' => 'td',
                'machine_name' => 'Titan Dryer 2',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.43',
                'machine_type' => 'td',
                'machine_name' => 'Titan Dryer 3',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.44',
                'machine_type' => 'td',
                'machine_name' => 'Titan Dryer 4',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.45',
                'machine_type' => 'td',
                'machine_name' => 'Titan Dryer 5',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
        ];
        Machine::insert($machines);
    }
}
