<?php

use App\Machine;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MachinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $machines = [
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.11',
                'machine_type' => 'rw',
                'machine_name' => 'W1',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.12',
                'machine_type' => 'rw',
                'machine_name' => 'W2',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.13',
                'machine_type' => 'rw',
                'machine_name' => 'W3',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.14',
                'machine_type' => 'rw',
                'machine_name' => 'W4',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.15',
                'machine_type' => 'rw',
                'machine_name' => 'W5',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 60,
                'additional_price' => 20,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.31',
                'machine_type' => 'rd',
                'machine_name' => 'D1',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.32',
                'machine_type' => 'rd',
                'machine_name' => 'D2',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.33',
                'machine_type' => 'rd',
                'machine_name' => 'D3',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.34',
                'machine_type' => 'rd',
                'machine_name' => 'D4',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.35',
                'machine_type' => 'rd',
                'machine_name' => 'D5',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 15,
                'additional_price' => 15,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.21',
                'machine_type' => 'tw',
                'machine_name' => 'TW1',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 90,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.22',
                'machine_type' => 'tw',
                'machine_name' => 'TW2',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 90,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.23',
                'machine_type' => 'tw',
                'machine_name' => 'TW3',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 90,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.24',
                'machine_type' => 'tw',
                'machine_name' => 'TW4',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 90,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.25',
                'machine_type' => 'tw',
                'machine_name' => 'TW5',
                'initial_time' => 39,
                'additional_time' => 12,
                'initial_price' => 90,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.41',
                'machine_type' => 'td',
                'machine_name' => 'TD1',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 30,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.42',
                'machine_type' => 'td',
                'machine_name' => 'TD2',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 30,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.43',
                'machine_type' => 'td',
                'machine_name' => 'TD3',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 30,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.44',
                'machine_type' => 'td',
                'machine_name' => 'TD4',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 30,
                'additional_price' => 30,
            ],
            [
                'id' => Str::uuid(),
                'ip_address' => '192.168.210.45',
                'machine_type' => 'td',
                'machine_name' => 'TD5',
                'initial_time' => 10,
                'additional_time' => 10,
                'initial_price' => 30,
                'additional_price' => 30,
            ],
        ];
        Machine::insert($machines);
    }
}
